---
neutron:
  rev: fb999fee1d632964f3d615e1a986b07409ba2245
  api_workers: 3
  agent_down_time: 20
  dhcp_dns_servers:
    - 8.8.8.8
    - 8.8.4.4
  service_plugins:
    - neutron.services.l3_router.l3_router_plugin.L3RouterPlugin
#    - neutron.services.loadbalancer.plugin.LoadBalancerPlugin
